require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'rails8-example/**/*'
    - 'rails8-sql-example/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
